# Generated by Django 3.0.3 on 2020-10-12 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mset', models.CharField(max_length=5)),
                ('foil', models.BooleanField(default=False)),
                ('alt_art', models.BooleanField(default=False)),
                ('my_price', models.IntegerField()),
                ('condition', models.CharField(choices=[('M', 'M'), ('NM', 'NM'), ('SP', 'SP'), ('HP', 'HP')], default='NM', max_length=2)),
                ('card_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plist.CardList')),
            ],
        ),
    ]
