# Generated by Django 3.0.3 on 2020-10-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plist', '0002_auto_20201013_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlist',
            name='name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
