# Generated by Django 2.0.2 on 2021-01-12 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plist', '0004_auto_20210112_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
