# Generated by Django 2.0.2 on 2021-02-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plist', '0005_auto_20210112_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='plist.CardList'),
        ),
        migrations.AlterField(
            model_name='card',
            name='my_price',
            field=models.FloatField(default=0),
        ),
    ]
